// Code generated by go-swagger; DO NOT EDIT.

package service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewServiceRepeatGreetParams creates a new ServiceRepeatGreetParams object
// with the default values initialized.
func NewServiceRepeatGreetParams() *ServiceRepeatGreetParams {
	var ()
	return &ServiceRepeatGreetParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewServiceRepeatGreetParamsWithTimeout creates a new ServiceRepeatGreetParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewServiceRepeatGreetParamsWithTimeout(timeout time.Duration) *ServiceRepeatGreetParams {
	var ()
	return &ServiceRepeatGreetParams{

		timeout: timeout,
	}
}

// NewServiceRepeatGreetParamsWithContext creates a new ServiceRepeatGreetParams object
// with the default values initialized, and the ability to set a context for a request
func NewServiceRepeatGreetParamsWithContext(ctx context.Context) *ServiceRepeatGreetParams {
	var ()
	return &ServiceRepeatGreetParams{

		Context: ctx,
	}
}

// NewServiceRepeatGreetParamsWithHTTPClient creates a new ServiceRepeatGreetParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewServiceRepeatGreetParamsWithHTTPClient(client *http.Client) *ServiceRepeatGreetParams {
	var ()
	return &ServiceRepeatGreetParams{
		HTTPClient: client,
	}
}

/*ServiceRepeatGreetParams contains all the parameters to send to the API endpoint
for the service repeat greet operation typically these are written to a http.Request
*/
type ServiceRepeatGreetParams struct {

	/*Name
	  The name to greet.

	*/
	Name *string
	/*TickerSecond
	  The ticker in second.

	*/
	TickerSecond *string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the service repeat greet params
func (o *ServiceRepeatGreetParams) WithTimeout(timeout time.Duration) *ServiceRepeatGreetParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the service repeat greet params
func (o *ServiceRepeatGreetParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the service repeat greet params
func (o *ServiceRepeatGreetParams) WithContext(ctx context.Context) *ServiceRepeatGreetParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the service repeat greet params
func (o *ServiceRepeatGreetParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the service repeat greet params
func (o *ServiceRepeatGreetParams) WithHTTPClient(client *http.Client) *ServiceRepeatGreetParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the service repeat greet params
func (o *ServiceRepeatGreetParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithName adds the name to the service repeat greet params
func (o *ServiceRepeatGreetParams) WithName(name *string) *ServiceRepeatGreetParams {
	o.SetName(name)
	return o
}

// SetName adds the name to the service repeat greet params
func (o *ServiceRepeatGreetParams) SetName(name *string) {
	o.Name = name
}

// WithTickerSecond adds the tickerSecond to the service repeat greet params
func (o *ServiceRepeatGreetParams) WithTickerSecond(tickerSecond *string) *ServiceRepeatGreetParams {
	o.SetTickerSecond(tickerSecond)
	return o
}

// SetTickerSecond adds the tickerSecond to the service repeat greet params
func (o *ServiceRepeatGreetParams) SetTickerSecond(tickerSecond *string) {
	o.TickerSecond = tickerSecond
}

// WriteToRequest writes these params to a swagger request
func (o *ServiceRepeatGreetParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Name != nil {

		// query param name
		var qrName string
		if o.Name != nil {
			qrName = *o.Name
		}
		qName := qrName
		if qName != "" {
			if err := r.SetQueryParam("name", qName); err != nil {
				return err
			}
		}

	}

	if o.TickerSecond != nil {

		// query param tickerSecond
		var qrTickerSecond string
		if o.TickerSecond != nil {
			qrTickerSecond = *o.TickerSecond
		}
		qTickerSecond := qrTickerSecond
		if qTickerSecond != "" {
			if err := r.SetQueryParam("tickerSecond", qTickerSecond); err != nil {
				return err
			}
		}

	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
