// Code generated by go-swagger; DO NOT EDIT.

package service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"grpc_gateway/http_client/models"
)

// NewServiceGreetParams creates a new ServiceGreetParams object
// with the default values initialized.
func NewServiceGreetParams() *ServiceGreetParams {
	var ()
	return &ServiceGreetParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewServiceGreetParamsWithTimeout creates a new ServiceGreetParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewServiceGreetParamsWithTimeout(timeout time.Duration) *ServiceGreetParams {
	var ()
	return &ServiceGreetParams{

		timeout: timeout,
	}
}

// NewServiceGreetParamsWithContext creates a new ServiceGreetParams object
// with the default values initialized, and the ability to set a context for a request
func NewServiceGreetParamsWithContext(ctx context.Context) *ServiceGreetParams {
	var ()
	return &ServiceGreetParams{

		Context: ctx,
	}
}

// NewServiceGreetParamsWithHTTPClient creates a new ServiceGreetParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewServiceGreetParamsWithHTTPClient(client *http.Client) *ServiceGreetParams {
	var ()
	return &ServiceGreetParams{
		HTTPClient: client,
	}
}

/*ServiceGreetParams contains all the parameters to send to the API endpoint
for the service greet operation typically these are written to a http.Request
*/
type ServiceGreetParams struct {

	/*Body*/
	Body *models.ServiceGreetRequest

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the service greet params
func (o *ServiceGreetParams) WithTimeout(timeout time.Duration) *ServiceGreetParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the service greet params
func (o *ServiceGreetParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the service greet params
func (o *ServiceGreetParams) WithContext(ctx context.Context) *ServiceGreetParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the service greet params
func (o *ServiceGreetParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the service greet params
func (o *ServiceGreetParams) WithHTTPClient(client *http.Client) *ServiceGreetParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the service greet params
func (o *ServiceGreetParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the service greet params
func (o *ServiceGreetParams) WithBody(body *models.ServiceGreetRequest) *ServiceGreetParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the service greet params
func (o *ServiceGreetParams) SetBody(body *models.ServiceGreetRequest) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *ServiceGreetParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
